name: "Treebeard Jupyter Notebook CI"
author: "treebeardtech"
description: "Automatically containerise and run notebooks"
inputs:
  api-key:
    description: "treebeard api key"
    required: false
  notebooks:
    description: "notebooks to run"
    required: false
  docker-username:
    description: ""
    required: false
  docker-password:
    description: ""
    required: false
  docker-image-name:
    description: "the name of the image built by treebeard"
    required: false
  docker-registry-prefix:
    description: "the prefix of your docker image name, use instead of docker-image-name to generate a default image name"
    required: false
  use-docker:
    description: "run treebeard inside repo2docker"
    required: false
    default: "true"
  debug:
    description: "Enable debug logging"
    required: false
    default: "false"
  path:
    description: "Path of the repo to run"
    required: false
    default: "."
  req-file-path:
    description: "Location of the requirements file (e.g. './test/environment.yml'), relative to the repo path"
    required: false
  usage-logging:
    required: false
    description: "provide usage metadata to inform project roadmap"
    default: "true"
runs:
  using: "node12"
  main: "dist/index.js"
