name: Action Integration Test

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install virtualenv ipython ipykernel
      - run: virtualenv --system-site-packages venvs\main
      - run: |
          . venvs\main\Scripts\activate.ps1
          python -m ipykernel install --user --name main
      - run: ipython kernelspec list
      - uses: ./
        with:
          use-docker: false
          path: ./examples/hello_treebeard
