name: Pytest
on: [push]

jobs:
  pytest:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Run
        run: |
          set -eux
          python -m pip install --upgrade pip pipenv
          pushd ./treebeard-lib
          pipenv install --dev --system --deploy
          pytest
