name: Pytest
on: [push, pull_request]

jobs:
  pytest:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Run
        run: |
          python -m pip install --upgrade pip pipenv
          pushd ./treebeard-lib
          pipenv install --dev --system --deploy
          pytest
