name: Pytest
on: [push, pull_request]

jobs:
  pytest:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: treebeardtech/treebeard@master
        with:
          notebooks: "treebeard-lib/run_tests.ipynb" # run: pytest
          api-key: ${{ secrets.TREEBEARD_API_KEY }}
