# name: Teams Integration Test
# # Tests which upload outputs to api.treebeard.io, requires treebeard API key
# on: [push]

# jobs:
#   gcp_docker_test:
#     timeout-minutes: 20
#     runs-on: ubuntu-latest
#     steps:
#       - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
#         with:
#           project_id: ${{ secrets.GCP_PROJECT_ID }}
#           service_account_key: ${{ secrets.GCP_SA_KEY }}
#           export_default_credentials: true
#       - run: gcloud auth configure-docker
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#         with:
#           python-version: 3.8
#       - uses: "./"
#         with:
#           api-key: ${{ secrets.TREEBEARD_API_KEY }}
#           docker-image-name: gcr.io/treebeard-259315/tests/custom-name/hello
#           path: "./examples/hello_treebeard"
#           debug: "true"
#       - run: docker inspect --type=image "gcr.io/treebeard-259315/tests/custom-name/hello:$(git rev-parse --abbrev-ref HEAD)-latest"

#   docker_hub_test:
#     timeout-minutes: 20
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#         with:
#           python-version: 3.8
#       - uses: "./"
#         with:
#           api-key: ${{ secrets.TREEBEARD_API_KEY }}
#           docker-username: "alextreebeard"
#           docker-password: "${{ secrets.DOCKER_PASSWORD }}"
#           docker-image-name: "treebeardtech/hello_treebeard"
#           path: "./examples/hello_treebeard"
#           debug: "true"
#       - run: docker inspect --type=image "docker.io/treebeardtech/hello_treebeard:$(git rev-parse --abbrev-ref HEAD)-latest"

#   secret_test:
#     timeout-minutes: 20
#     runs-on: ubuntu-latest
#     steps:
#       - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
#         with:
#           project_id: ${{ secrets.GCP_PROJECT_ID }}
#           service_account_key: ${{ secrets.GCP_SA_KEY }}
#           export_default_credentials: true
#       - run: gcloud auth configure-docker
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#         with:
#           python-version: 3.8
#       - uses: "./"
#         with:
#           api-key: ${{ secrets.TREEBEARD_API_KEY }}
#           docker-registry-prefix: gcr.io/treebeard-259315/tests
#           path: "./examples/google_cloud_storage"
#           debug: "true"
#         env:
#           TB_GCP_SERVICE_ACCOUNT_KEY: "${{ secrets.GCP_SA_KEY }}" # TB_ prefix directs treebeard to forward env to container

#   upload_test:
#     timeout-minutes: 20
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#         with:
#           python-version: 3.8
#       - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
#         with:
#           project_id: ${{ secrets.GCP_PROJECT_ID }}
#           service_account_key: ${{ secrets.GCP_SA_KEY }}
#           export_default_credentials: true
#       - run: gcloud auth configure-docker
#       - uses: "./"
#         with:
#           api-key: ${{ secrets.TREEBEARD_API_KEY }}
#           docker-registry-prefix: gcr.io/treebeard-259315/tests
#           debug: "true"
#           path: "./integration-test/virtualenv"
#         env:
#           TREEBEARD_USER_NAME: "d8a0c5b6c9"
#       - name: Check uploads
#         run: |
#           branch=$(git rev-parse --abbrev-ref HEAD)
#           wget "https://api.treebeard.io/d8a0c5b6c9/virtualenv/$branch/main.ipynb"
#           wget "https://api.treebeard.io/d8a0c5b6c9/virtualenv/$branch/another.ipynb"
#           wget "https://api.treebeard.io/d8a0c5b6c9/virtualenv/$branch/subdir/another.ipynb"
