on: push
jobs:
  run:
    runs-on: windows-latest
    name: Run treebeard
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt # Manually install python deps as running dockerless
        working-directory: "./examples/hello_treebeard"
      - uses: ./
        with:
          use-docker: false
          path: ./examples/hello_treebeard
